/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1085473_8_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1085473_1[] = { "circle", "idle", "left_right", "up_down" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1085473_7_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_1085473_7_axes_size = 6;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1085473_7 = {
    7, // uint32_t blockId
    4, // int implementationVersion
    6, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1085473_7[42] = { 2.693430420011282, 1.0157819348706103, 1.794532523717394, 1.7436945153394154, 1.4801144448659518, 1.8111947203439618, 0.8940439563868536, 2.334052361781546, 0.5274026372520617, 0.3882205555756708, 1.9925292474970762, 2.4216556785355987, 1.4750849709326628, 0.6887761805305868, 1.4370224168370462, -0.6606464689155439, 0.8279785558301072, 1.811303494664112, 1.7557438135626797, 1.1577596479199639, 0.33560893011285725, 0.6180861446706397, -0.03818607108396704, -0.1496592923252621, 1.924643753717343, 2.218323776816994, -0.012409727333019708, -0.6997648373985688, 0.6516147897944351, 0.024114101318372508, -0.14663929269198267, 1.8519516592912941, 1.9776155992408664, -0.05349647802272512, -0.6837654416204285, 0.6705823390676046, -0.07380197261316518, -0.25777522784013096, 1.8427832227679763, 1.929550640663725, 0.0413516570194615, -0.6244258195763683 };
const float ei_dn_standard_scaler_scale_1085473_7[42] = { 1.1345153157788521, 0.7907360413199752, 0.4996013425595081, 2.8951505894621046, 0.7576849232494365, 2.8152035346203084, 2.6679786984281457, 1.1386961299504865, 0.9088089249369191, 0.46348646361097323, 2.7477229728514976, 0.7360569229732132, 3.1376344814304673, 2.936746594649772, 1.6217624948576088, 0.8979972063178221, 0.5155073480663027, 2.6224344707036664, 0.7003068835922545, 2.5159475845380066, 2.544875433103832, 2.1187276559888653, 1.2615253904439336, 0.8273011638304607, 2.6912021487470676, 0.7450694759195249, 0.9981144559570562, 0.9680786754542318, 1.730735174722595, 1.3124507576604125, 0.7932379715161861, 2.421459703167158, 0.6858718810818508, 0.8845312158938041, 0.9032413968716781, 1.994166106948721, 1.4371691031671017, 0.8861176605205475, 2.4733945331107288, 0.688718258394659, 0.8986197273685694, 0.9163883434171138 };
const float ei_dn_standard_scaler_var_1085473_7[42] = { 0.776925317005454, 1.599325757418187, 4.006386155697983, 0.11930473587014206, 1.7418979534066703, 0.12617705939592144, 0.140486723708896, 0.7712307031168615, 1.2107509912164325, 4.655066508890011, 0.13245065505038, 1.8457683570685612, 0.10157698122091056, 0.11594901199039453, 0.3802117155342645, 1.2400809297056317, 3.7629658740363188, 0.14540880665154113, 2.0390280938708876, 0.15797807655979731, 0.15440698448099086, 0.22276642176673322, 0.6283592435728055, 1.4610757390958375, 0.13807255398623494, 1.801384646729991, 1.0037817807927651, 1.0670350676439164, 0.33384029820012173, 0.5805424269462026, 1.5892528885083823, 0.17054755897114973, 2.125758887047935, 1.2781260065112743, 1.2257229917839698, 0.2514648796054717, 0.4841548157397232, 1.2735535640037916, 0.16346064449028397, 2.1082242611909248, 1.2383633865323527, 1.1908056524470048 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1085473_7 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1085473_7,
    .mean_data_len = 42,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1085473_7,
    .scale_data_len = 42,
    .var_data = (float *)ei_dn_standard_scaler_var_1085473_7,
    .var_data_len = 42
};
ei_data_normalization_t ei_data_normalization_config_1085473_7 = {
    (void *) &ei_data_normalization_standard_scaler_config_1085473_7, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1085473_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1085473_1[ei_dsp_blocks_1085473_1_size] = {
    { // DSP block 7
        7,
        42, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1085473_7, // pointer to config struct
        ei_dsp_config_1085473_7_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1085473_7_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1085473_7, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1085473_8 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1085473_8_init,
    .model_invoke = &tflite_learn_1085473_8_invoke,
    .model_reset = &tflite_learn_1085473_8_reset,
    .model_input = &tflite_learn_1085473_8_input,
    .model_output = &tflite_learn_1085473_8_output,
};

const uint8_t ei_output_tensors_indices_1085473_8[1] = { 0 };
const uint8_t ei_output_tensors_size_1085473_8 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1085473_8 = {
    .implementation_version = 1,
    .block_id = 8,
    .output_tensors_indices = ei_output_tensors_indices_1085473_8,
    .output_tensors_size = ei_output_tensors_size_1085473_8,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1085473_8,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1085473_1_size = 1;
const uint32_t ei_learning_block_1085473_8_inputs[1] = { 7 };
const uint8_t ei_learning_block_1085473_8_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1085473_1[ei_learning_blocks_1085473_1_size] = {
    {
        8,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1085473_8,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1085473_8_inputs,
        ei_learning_block_1085473_8_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_1085473_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1085473_1[ei_postprocessing_blocks_1085473_1_size] = {
    {
        .block_id = 8,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 8
    },
};

const uint8_t freeform_outputs_1085473_1_size = 0;

uint32_t *freeform_outputs_1085473_1 = nullptr;

const ei_impulse_t impulse_1085473_1 = {
    .project_id = 1085473,
    .project_owner = "matteoMD",
    .project_name = "HMI Edge AI",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 42,
    .raw_sample_count = 50,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 50 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 40,
    .frequency = 25,

    .dsp_blocks_size = ei_dsp_blocks_1085473_1_size,
    .dsp_blocks = ei_dsp_blocks_1085473_1,

    .learning_blocks_size = ei_learning_blocks_1085473_1_size,
    .learning_blocks = ei_learning_blocks_1085473_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1085473_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1085473_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "accX + accY + accZ + gyrX + gyrY + gyrZ",
    .slice_size = (50/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_1085473_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1085473_1_size,
    .freeform_outputs = freeform_outputs_1085473_1
};

ei_impulse_handle_t impulse_handle_1085473_1 = ei_impulse_handle_t( &impulse_1085473_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1085473_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1085473_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1085473_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1085473_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
